# Generated by Django 4.1.1 on 2022-09-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olimp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sciences', models.TextField()),
                ('audience', models.TextField()),
                ('start_dates', models.DateTimeField(blank=True, null=True)),
                ('finish_dates', models.DateTimeField(blank=True, null=True)),
                ('site', models.URLField(null=True)),
            ],
        ),
    ]
