# Generated by Django 4.1.1 on 2022-10-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_olimp_tegs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olimp',
            old_name='sciences',
            new_name='information',
        ),
    ]
